name: 'action-download-workflow-artifact'
description: 'Downloads a GitHub artifact for a workflow (from a different branch)'
author: 'Billy Vong'
inputs:
  artifact:
    description: 'The name of the artifact to download'
    required: true
  branch:
    description: 'The branch to download artifacts from'
    default: 'main'
    required: true
  github-token:
    description: 'GitHub token'
    default: '${{ github.token }}'
    required: true
  path:
    description: 'The path to download the artifact to'
    required: false
  workflow:
    description: 'The workflow name to download artifact from. By default, the workflow that uses this action will be used.'
    required: false
  workflowEvent:
    description: 'Only search for workflows that were triggered by a specific workflow event (e.g. `push`)'
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'
