name: '[integration] test'

on: pull_request


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: ./
        with:
          artifact: integration-test-artifact
          branch: main
          workflow: '[integration] save artifact'
          path: download

      - run: ls download/README.md
