name: test

on:
  push:
    branches:
      - main
  pull_request:


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          cache: yarn
          node-version: 16.x

      - run: yarn install
      - run: yarn lint
      - run: yarn test

  integration-test:
    name: integration test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          cache: yarn
          node-version: 16.x

      - run: yarn install
      - run: yarn dist

      - uses: ./
        with:
          artifact: integration-test-artifact
          branch: main
          workflow: 'integration test setup'
          path: download

      - run: ls download/README.md
